// Code generated by Kitex v0.8.0. DO NOT EDIT.

package howellrpcservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	howell_rpc "howell/howell_rpc/kitex_gen/coder/hao/howell_rpc"
)

func serviceInfo() *kitex.ServiceInfo {
	return howellRpcServiceServiceInfo
}

var howellRpcServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "HowellRpcService"
	handlerType := (*howell_rpc.HowellRpcService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateCpsRebateDiscounts": kitex.NewMethodInfo(createCpsRebateDiscountsHandler, newHowellRpcServiceCreateCpsRebateDiscountsArgs, newHowellRpcServiceCreateCpsRebateDiscountsResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "howell_rpc",
		"ServiceFilePath": `idl/howell_rpc.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func createCpsRebateDiscountsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsArgs)
	realResult := result.(*howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsResult)
	success, err := handler.(howell_rpc.HowellRpcService).CreateCpsRebateDiscounts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHowellRpcServiceCreateCpsRebateDiscountsArgs() interface{} {
	return howell_rpc.NewHowellRpcServiceCreateCpsRebateDiscountsArgs()
}

func newHowellRpcServiceCreateCpsRebateDiscountsResult() interface{} {
	return howell_rpc.NewHowellRpcServiceCreateCpsRebateDiscountsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCpsRebateDiscounts(ctx context.Context, req *howell_rpc.CreateCpsRebateDiscountsRequest) (r *howell_rpc.CreateCpsRebateDiscountsResponse, err error) {
	var _args howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsArgs
	_args.Req = req
	var _result howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsResult
	if err = p.c.Call(ctx, "CreateCpsRebateDiscounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
