// Code generated by Kitex v0.8.0. DO NOT EDIT.

package howellrpcservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	howell_rpc "howell/howell_rpc/kitex_gen/coder/hao/howell_rpc"
)

func serviceInfo() *kitex.ServiceInfo {
	return howellRpcServiceServiceInfo
}

var howellRpcServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "HowellRpcService"
	handlerType := (*howell_rpc.HowellRpcService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateCpsRebateDiscounts": kitex.NewMethodInfo(createCpsRebateDiscountsHandler, newHowellRpcServiceCreateCpsRebateDiscountsArgs, newHowellRpcServiceCreateCpsRebateDiscountsResult, false),
		"UpdateCpsRebateDiscounts": kitex.NewMethodInfo(updateCpsRebateDiscountsHandler, newHowellRpcServiceUpdateCpsRebateDiscountsArgs, newHowellRpcServiceUpdateCpsRebateDiscountsResult, false),
		"MGetCpsRebateDiscounts":   kitex.NewMethodInfo(mGetCpsRebateDiscountsHandler, newHowellRpcServiceMGetCpsRebateDiscountsArgs, newHowellRpcServiceMGetCpsRebateDiscountsResult, false),
		"QueryCpsRebateDiscounts":  kitex.NewMethodInfo(queryCpsRebateDiscountsHandler, newHowellRpcServiceQueryCpsRebateDiscountsArgs, newHowellRpcServiceQueryCpsRebateDiscountsResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "howell_rpc",
		"ServiceFilePath": `../idl/howell_rpc.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.8.0",
		Extra:           extra,
	}
	return svcInfo
}

func createCpsRebateDiscountsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsArgs)
	realResult := result.(*howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsResult)
	success, err := handler.(howell_rpc.HowellRpcService).CreateCpsRebateDiscounts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHowellRpcServiceCreateCpsRebateDiscountsArgs() interface{} {
	return howell_rpc.NewHowellRpcServiceCreateCpsRebateDiscountsArgs()
}

func newHowellRpcServiceCreateCpsRebateDiscountsResult() interface{} {
	return howell_rpc.NewHowellRpcServiceCreateCpsRebateDiscountsResult()
}

func updateCpsRebateDiscountsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*howell_rpc.HowellRpcServiceUpdateCpsRebateDiscountsArgs)
	realResult := result.(*howell_rpc.HowellRpcServiceUpdateCpsRebateDiscountsResult)
	success, err := handler.(howell_rpc.HowellRpcService).UpdateCpsRebateDiscounts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHowellRpcServiceUpdateCpsRebateDiscountsArgs() interface{} {
	return howell_rpc.NewHowellRpcServiceUpdateCpsRebateDiscountsArgs()
}

func newHowellRpcServiceUpdateCpsRebateDiscountsResult() interface{} {
	return howell_rpc.NewHowellRpcServiceUpdateCpsRebateDiscountsResult()
}

func mGetCpsRebateDiscountsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*howell_rpc.HowellRpcServiceMGetCpsRebateDiscountsArgs)
	realResult := result.(*howell_rpc.HowellRpcServiceMGetCpsRebateDiscountsResult)
	success, err := handler.(howell_rpc.HowellRpcService).MGetCpsRebateDiscounts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHowellRpcServiceMGetCpsRebateDiscountsArgs() interface{} {
	return howell_rpc.NewHowellRpcServiceMGetCpsRebateDiscountsArgs()
}

func newHowellRpcServiceMGetCpsRebateDiscountsResult() interface{} {
	return howell_rpc.NewHowellRpcServiceMGetCpsRebateDiscountsResult()
}

func queryCpsRebateDiscountsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*howell_rpc.HowellRpcServiceQueryCpsRebateDiscountsArgs)
	realResult := result.(*howell_rpc.HowellRpcServiceQueryCpsRebateDiscountsResult)
	success, err := handler.(howell_rpc.HowellRpcService).QueryCpsRebateDiscounts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHowellRpcServiceQueryCpsRebateDiscountsArgs() interface{} {
	return howell_rpc.NewHowellRpcServiceQueryCpsRebateDiscountsArgs()
}

func newHowellRpcServiceQueryCpsRebateDiscountsResult() interface{} {
	return howell_rpc.NewHowellRpcServiceQueryCpsRebateDiscountsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCpsRebateDiscounts(ctx context.Context, req *howell_rpc.CreateCpsRebateDiscountsRequest) (r *howell_rpc.CreateCpsRebateDiscountsResponse, err error) {
	var _args howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsArgs
	_args.Req = req
	var _result howell_rpc.HowellRpcServiceCreateCpsRebateDiscountsResult
	if err = p.c.Call(ctx, "CreateCpsRebateDiscounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCpsRebateDiscounts(ctx context.Context, req *howell_rpc.UpdateCpsRebateDiscountsRequest) (r *howell_rpc.UpdateCpsRebateDiscountsResponse, err error) {
	var _args howell_rpc.HowellRpcServiceUpdateCpsRebateDiscountsArgs
	_args.Req = req
	var _result howell_rpc.HowellRpcServiceUpdateCpsRebateDiscountsResult
	if err = p.c.Call(ctx, "UpdateCpsRebateDiscounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MGetCpsRebateDiscounts(ctx context.Context, req *howell_rpc.MGetCpsRebateDiscountsRequest) (r *howell_rpc.MGetCpsRebateDiscountsResponse, err error) {
	var _args howell_rpc.HowellRpcServiceMGetCpsRebateDiscountsArgs
	_args.Req = req
	var _result howell_rpc.HowellRpcServiceMGetCpsRebateDiscountsResult
	if err = p.c.Call(ctx, "MGetCpsRebateDiscounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryCpsRebateDiscounts(ctx context.Context, req *howell_rpc.QueryCpsRebateDiscountsRequest) (r *howell_rpc.QueryCpsRebateDiscountsResponse, err error) {
	var _args howell_rpc.HowellRpcServiceQueryCpsRebateDiscountsArgs
	_args.Req = req
	var _result howell_rpc.HowellRpcServiceQueryCpsRebateDiscountsResult
	if err = p.c.Call(ctx, "QueryCpsRebateDiscounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
