// Code generated by thriftgo (0.3.6). DO NOT EDIT.

package howell_rpc

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"howell/howell_rpc/kitex_gen/base"
	"howell/howell_rpc/kitex_gen/models"
	"strings"
)

type CreateCpsRebateDiscountsRequest struct {
	CRDEntity *models.CpsRebateDiscounts `thrift:"CRDEntity,1,required" frugal:"1,required,models.CpsRebateDiscounts" json:"CRDEntity"`
	Base      *base.Base                 `thrift:"Base,255" frugal:"255,default,base.Base" json:"Base"`
}

func NewCreateCpsRebateDiscountsRequest() *CreateCpsRebateDiscountsRequest {
	return &CreateCpsRebateDiscountsRequest{}
}

func (p *CreateCpsRebateDiscountsRequest) InitDefault() {
	*p = CreateCpsRebateDiscountsRequest{}
}

var CreateCpsRebateDiscountsRequest_CRDEntity_DEFAULT *models.CpsRebateDiscounts

func (p *CreateCpsRebateDiscountsRequest) GetCRDEntity() (v *models.CpsRebateDiscounts) {
	if !p.IsSetCRDEntity() {
		return CreateCpsRebateDiscountsRequest_CRDEntity_DEFAULT
	}
	return p.CRDEntity
}

var CreateCpsRebateDiscountsRequest_Base_DEFAULT *base.Base

func (p *CreateCpsRebateDiscountsRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return CreateCpsRebateDiscountsRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *CreateCpsRebateDiscountsRequest) SetCRDEntity(val *models.CpsRebateDiscounts) {
	p.CRDEntity = val
}
func (p *CreateCpsRebateDiscountsRequest) SetBase(val *base.Base) {
	p.Base = val
}

var fieldIDToName_CreateCpsRebateDiscountsRequest = map[int16]string{
	1:   "CRDEntity",
	255: "Base",
}

func (p *CreateCpsRebateDiscountsRequest) IsSetCRDEntity() bool {
	return p.CRDEntity != nil
}

func (p *CreateCpsRebateDiscountsRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *CreateCpsRebateDiscountsRequest) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetCRDEntity bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetCRDEntity = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 255:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField255(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetCRDEntity {
		fieldId = 1
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_CreateCpsRebateDiscountsRequest[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_CreateCpsRebateDiscountsRequest[fieldId]))
}

func (p *CreateCpsRebateDiscountsRequest) ReadField1(iprot thrift.TProtocol) error {
	p.CRDEntity = models.NewCpsRebateDiscounts()
	if err := p.CRDEntity.Read(iprot); err != nil {
		return err
	}
	return nil
}
func (p *CreateCpsRebateDiscountsRequest) ReadField255(iprot thrift.TProtocol) error {
	p.Base = base.NewBase()
	if err := p.Base.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *CreateCpsRebateDiscountsRequest) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CreateCpsRebateDiscountsRequest"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField255(oprot); err != nil {
			fieldId = 255
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *CreateCpsRebateDiscountsRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("CRDEntity", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.CRDEntity.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *CreateCpsRebateDiscountsRequest) writeField255(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("Base", thrift.STRUCT, 255); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Base.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 end error: ", p), err)
}

func (p *CreateCpsRebateDiscountsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCpsRebateDiscountsRequest(%+v)", *p)

}

func (p *CreateCpsRebateDiscountsRequest) DeepEqual(ano *CreateCpsRebateDiscountsRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.CRDEntity) {
		return false
	}
	if !p.Field255DeepEqual(ano.Base) {
		return false
	}
	return true
}

func (p *CreateCpsRebateDiscountsRequest) Field1DeepEqual(src *models.CpsRebateDiscounts) bool {

	if !p.CRDEntity.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CreateCpsRebateDiscountsRequest) Field255DeepEqual(src *base.Base) bool {

	if !p.Base.DeepEqual(src) {
		return false
	}
	return true
}

type CreateCpsRebateDiscountsResponse struct {
	EntityId *string        `thrift:"EntityId,1,optional" frugal:"1,optional,string" json:"EntityId,omitempty"`
	BaseResp *base.BaseResp `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewCreateCpsRebateDiscountsResponse() *CreateCpsRebateDiscountsResponse {
	return &CreateCpsRebateDiscountsResponse{}
}

func (p *CreateCpsRebateDiscountsResponse) InitDefault() {
	*p = CreateCpsRebateDiscountsResponse{}
}

var CreateCpsRebateDiscountsResponse_EntityId_DEFAULT string

func (p *CreateCpsRebateDiscountsResponse) GetEntityId() (v string) {
	if !p.IsSetEntityId() {
		return CreateCpsRebateDiscountsResponse_EntityId_DEFAULT
	}
	return *p.EntityId
}

var CreateCpsRebateDiscountsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CreateCpsRebateDiscountsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateCpsRebateDiscountsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateCpsRebateDiscountsResponse) SetEntityId(val *string) {
	p.EntityId = val
}
func (p *CreateCpsRebateDiscountsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

var fieldIDToName_CreateCpsRebateDiscountsResponse = map[int16]string{
	1:   "EntityId",
	255: "BaseResp",
}

func (p *CreateCpsRebateDiscountsResponse) IsSetEntityId() bool {
	return p.EntityId != nil
}

func (p *CreateCpsRebateDiscountsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateCpsRebateDiscountsResponse) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 255:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField255(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_CreateCpsRebateDiscountsResponse[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *CreateCpsRebateDiscountsResponse) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.EntityId = &v
	}
	return nil
}
func (p *CreateCpsRebateDiscountsResponse) ReadField255(iprot thrift.TProtocol) error {
	p.BaseResp = base.NewBaseResp()
	if err := p.BaseResp.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *CreateCpsRebateDiscountsResponse) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CreateCpsRebateDiscountsResponse"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField255(oprot); err != nil {
			fieldId = 255
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *CreateCpsRebateDiscountsResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetEntityId() {
		if err = oprot.WriteFieldBegin("EntityId", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.EntityId); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *CreateCpsRebateDiscountsResponse) writeField255(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("BaseResp", thrift.STRUCT, 255); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 end error: ", p), err)
}

func (p *CreateCpsRebateDiscountsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCpsRebateDiscountsResponse(%+v)", *p)

}

func (p *CreateCpsRebateDiscountsResponse) DeepEqual(ano *CreateCpsRebateDiscountsResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EntityId) {
		return false
	}
	if !p.Field255DeepEqual(ano.BaseResp) {
		return false
	}
	return true
}

func (p *CreateCpsRebateDiscountsResponse) Field1DeepEqual(src *string) bool {

	if p.EntityId == src {
		return true
	} else if p.EntityId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.EntityId, *src) != 0 {
		return false
	}
	return true
}
func (p *CreateCpsRebateDiscountsResponse) Field255DeepEqual(src *base.BaseResp) bool {

	if !p.BaseResp.DeepEqual(src) {
		return false
	}
	return true
}

type MGetCpsRebateDiscountsRequest struct {
	EntityIdList []string   `thrift:"EntityIdList,1,required" frugal:"1,required,list<string>" json:"EntityIdList"`
	Base         *base.Base `thrift:"Base,255" frugal:"255,default,base.Base" json:"Base"`
}

func NewMGetCpsRebateDiscountsRequest() *MGetCpsRebateDiscountsRequest {
	return &MGetCpsRebateDiscountsRequest{}
}

func (p *MGetCpsRebateDiscountsRequest) InitDefault() {
	*p = MGetCpsRebateDiscountsRequest{}
}

func (p *MGetCpsRebateDiscountsRequest) GetEntityIdList() (v []string) {
	return p.EntityIdList
}

var MGetCpsRebateDiscountsRequest_Base_DEFAULT *base.Base

func (p *MGetCpsRebateDiscountsRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return MGetCpsRebateDiscountsRequest_Base_DEFAULT
	}
	return p.Base
}
func (p *MGetCpsRebateDiscountsRequest) SetEntityIdList(val []string) {
	p.EntityIdList = val
}
func (p *MGetCpsRebateDiscountsRequest) SetBase(val *base.Base) {
	p.Base = val
}

var fieldIDToName_MGetCpsRebateDiscountsRequest = map[int16]string{
	1:   "EntityIdList",
	255: "Base",
}

func (p *MGetCpsRebateDiscountsRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *MGetCpsRebateDiscountsRequest) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetEntityIdList bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetEntityIdList = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 255:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField255(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetEntityIdList {
		fieldId = 1
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MGetCpsRebateDiscountsRequest[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_MGetCpsRebateDiscountsRequest[fieldId]))
}

func (p *MGetCpsRebateDiscountsRequest) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.EntityIdList = make([]string, 0, size)
	for i := 0; i < size; i++ {

		var _elem string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_elem = v
		}

		p.EntityIdList = append(p.EntityIdList, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}
func (p *MGetCpsRebateDiscountsRequest) ReadField255(iprot thrift.TProtocol) error {
	p.Base = base.NewBase()
	if err := p.Base.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MGetCpsRebateDiscountsRequest) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("MGetCpsRebateDiscountsRequest"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField255(oprot); err != nil {
			fieldId = 255
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MGetCpsRebateDiscountsRequest) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("EntityIdList", thrift.LIST, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRING, len(p.EntityIdList)); err != nil {
		return err
	}
	for _, v := range p.EntityIdList {
		if err := oprot.WriteString(v); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MGetCpsRebateDiscountsRequest) writeField255(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("Base", thrift.STRUCT, 255); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Base.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 end error: ", p), err)
}

func (p *MGetCpsRebateDiscountsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MGetCpsRebateDiscountsRequest(%+v)", *p)

}

func (p *MGetCpsRebateDiscountsRequest) DeepEqual(ano *MGetCpsRebateDiscountsRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EntityIdList) {
		return false
	}
	if !p.Field255DeepEqual(ano.Base) {
		return false
	}
	return true
}

func (p *MGetCpsRebateDiscountsRequest) Field1DeepEqual(src []string) bool {

	if len(p.EntityIdList) != len(src) {
		return false
	}
	for i, v := range p.EntityIdList {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *MGetCpsRebateDiscountsRequest) Field255DeepEqual(src *base.Base) bool {

	if !p.Base.DeepEqual(src) {
		return false
	}
	return true
}

type MGetCpsRebateDiscountsResponse struct {
	EntityMap map[string]*models.CpsRebateDiscounts `thrift:"EntityMap,1,optional" frugal:"1,optional,map<string:models.CpsRebateDiscounts>" json:"EntityMap,omitempty"`
	BaseResp  *base.BaseResp                        `thrift:"BaseResp,255" frugal:"255,default,base.BaseResp" json:"BaseResp"`
}

func NewMGetCpsRebateDiscountsResponse() *MGetCpsRebateDiscountsResponse {
	return &MGetCpsRebateDiscountsResponse{}
}

func (p *MGetCpsRebateDiscountsResponse) InitDefault() {
	*p = MGetCpsRebateDiscountsResponse{}
}

var MGetCpsRebateDiscountsResponse_EntityMap_DEFAULT map[string]*models.CpsRebateDiscounts

func (p *MGetCpsRebateDiscountsResponse) GetEntityMap() (v map[string]*models.CpsRebateDiscounts) {
	if !p.IsSetEntityMap() {
		return MGetCpsRebateDiscountsResponse_EntityMap_DEFAULT
	}
	return p.EntityMap
}

var MGetCpsRebateDiscountsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *MGetCpsRebateDiscountsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return MGetCpsRebateDiscountsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *MGetCpsRebateDiscountsResponse) SetEntityMap(val map[string]*models.CpsRebateDiscounts) {
	p.EntityMap = val
}
func (p *MGetCpsRebateDiscountsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

var fieldIDToName_MGetCpsRebateDiscountsResponse = map[int16]string{
	1:   "EntityMap",
	255: "BaseResp",
}

func (p *MGetCpsRebateDiscountsResponse) IsSetEntityMap() bool {
	return p.EntityMap != nil
}

func (p *MGetCpsRebateDiscountsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *MGetCpsRebateDiscountsResponse) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.MAP {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 255:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField255(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MGetCpsRebateDiscountsResponse[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MGetCpsRebateDiscountsResponse) ReadField1(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return err
	}
	p.EntityMap = make(map[string]*models.CpsRebateDiscounts, size)
	for i := 0; i < size; i++ {
		var _key string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_key = v
		}
		_val := models.NewCpsRebateDiscounts()
		if err := _val.Read(iprot); err != nil {
			return err
		}

		p.EntityMap[_key] = _val
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return err
	}
	return nil
}
func (p *MGetCpsRebateDiscountsResponse) ReadField255(iprot thrift.TProtocol) error {
	p.BaseResp = base.NewBaseResp()
	if err := p.BaseResp.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MGetCpsRebateDiscountsResponse) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("MGetCpsRebateDiscountsResponse"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField255(oprot); err != nil {
			fieldId = 255
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MGetCpsRebateDiscountsResponse) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetEntityMap() {
		if err = oprot.WriteFieldBegin("EntityMap", thrift.MAP, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.EntityMap)); err != nil {
			return err
		}
		for k, v := range p.EntityMap {
			if err := oprot.WriteString(k); err != nil {
				return err
			}
			if err := v.Write(oprot); err != nil {
				return err
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MGetCpsRebateDiscountsResponse) writeField255(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("BaseResp", thrift.STRUCT, 255); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 end error: ", p), err)
}

func (p *MGetCpsRebateDiscountsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MGetCpsRebateDiscountsResponse(%+v)", *p)

}

func (p *MGetCpsRebateDiscountsResponse) DeepEqual(ano *MGetCpsRebateDiscountsResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EntityMap) {
		return false
	}
	if !p.Field255DeepEqual(ano.BaseResp) {
		return false
	}
	return true
}

func (p *MGetCpsRebateDiscountsResponse) Field1DeepEqual(src map[string]*models.CpsRebateDiscounts) bool {

	if len(p.EntityMap) != len(src) {
		return false
	}
	for k, v := range p.EntityMap {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *MGetCpsRebateDiscountsResponse) Field255DeepEqual(src *base.BaseResp) bool {

	if !p.BaseResp.DeepEqual(src) {
		return false
	}
	return true
}

type HowellRpcService interface {
	CreateCpsRebateDiscounts(ctx context.Context, req *CreateCpsRebateDiscountsRequest) (r *CreateCpsRebateDiscountsResponse, err error)

	MGetCpsRebateDiscounts(ctx context.Context, req *MGetCpsRebateDiscountsRequest) (r *MGetCpsRebateDiscountsResponse, err error)
}

type HowellRpcServiceClient struct {
	c thrift.TClient
}

func NewHowellRpcServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *HowellRpcServiceClient {
	return &HowellRpcServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewHowellRpcServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *HowellRpcServiceClient {
	return &HowellRpcServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewHowellRpcServiceClient(c thrift.TClient) *HowellRpcServiceClient {
	return &HowellRpcServiceClient{
		c: c,
	}
}

func (p *HowellRpcServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *HowellRpcServiceClient) CreateCpsRebateDiscounts(ctx context.Context, req *CreateCpsRebateDiscountsRequest) (r *CreateCpsRebateDiscountsResponse, err error) {
	var _args HowellRpcServiceCreateCpsRebateDiscountsArgs
	_args.Req = req
	var _result HowellRpcServiceCreateCpsRebateDiscountsResult
	if err = p.Client_().Call(ctx, "CreateCpsRebateDiscounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *HowellRpcServiceClient) MGetCpsRebateDiscounts(ctx context.Context, req *MGetCpsRebateDiscountsRequest) (r *MGetCpsRebateDiscountsResponse, err error) {
	var _args HowellRpcServiceMGetCpsRebateDiscountsArgs
	_args.Req = req
	var _result HowellRpcServiceMGetCpsRebateDiscountsResult
	if err = p.Client_().Call(ctx, "MGetCpsRebateDiscounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type HowellRpcServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      HowellRpcService
}

func (p *HowellRpcServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *HowellRpcServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *HowellRpcServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewHowellRpcServiceProcessor(handler HowellRpcService) *HowellRpcServiceProcessor {
	self := &HowellRpcServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("CreateCpsRebateDiscounts", &howellRpcServiceProcessorCreateCpsRebateDiscounts{handler: handler})
	self.AddToProcessorMap("MGetCpsRebateDiscounts", &howellRpcServiceProcessorMGetCpsRebateDiscounts{handler: handler})
	return self
}
func (p *HowellRpcServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type howellRpcServiceProcessorCreateCpsRebateDiscounts struct {
	handler HowellRpcService
}

func (p *howellRpcServiceProcessorCreateCpsRebateDiscounts) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := HowellRpcServiceCreateCpsRebateDiscountsArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("CreateCpsRebateDiscounts", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := HowellRpcServiceCreateCpsRebateDiscountsResult{}
	var retval *CreateCpsRebateDiscountsResponse
	if retval, err2 = p.handler.CreateCpsRebateDiscounts(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing CreateCpsRebateDiscounts: "+err2.Error())
		oprot.WriteMessageBegin("CreateCpsRebateDiscounts", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("CreateCpsRebateDiscounts", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type howellRpcServiceProcessorMGetCpsRebateDiscounts struct {
	handler HowellRpcService
}

func (p *howellRpcServiceProcessorMGetCpsRebateDiscounts) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := HowellRpcServiceMGetCpsRebateDiscountsArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("MGetCpsRebateDiscounts", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := HowellRpcServiceMGetCpsRebateDiscountsResult{}
	var retval *MGetCpsRebateDiscountsResponse
	if retval, err2 = p.handler.MGetCpsRebateDiscounts(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing MGetCpsRebateDiscounts: "+err2.Error())
		oprot.WriteMessageBegin("MGetCpsRebateDiscounts", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("MGetCpsRebateDiscounts", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type HowellRpcServiceCreateCpsRebateDiscountsArgs struct {
	Req *CreateCpsRebateDiscountsRequest `thrift:"req,1" frugal:"1,default,CreateCpsRebateDiscountsRequest" json:"req"`
}

func NewHowellRpcServiceCreateCpsRebateDiscountsArgs() *HowellRpcServiceCreateCpsRebateDiscountsArgs {
	return &HowellRpcServiceCreateCpsRebateDiscountsArgs{}
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) InitDefault() {
	*p = HowellRpcServiceCreateCpsRebateDiscountsArgs{}
}

var HowellRpcServiceCreateCpsRebateDiscountsArgs_Req_DEFAULT *CreateCpsRebateDiscountsRequest

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) GetReq() (v *CreateCpsRebateDiscountsRequest) {
	if !p.IsSetReq() {
		return HowellRpcServiceCreateCpsRebateDiscountsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) SetReq(val *CreateCpsRebateDiscountsRequest) {
	p.Req = val
}

var fieldIDToName_HowellRpcServiceCreateCpsRebateDiscountsArgs = map[int16]string{
	1: "req",
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_HowellRpcServiceCreateCpsRebateDiscountsArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewCreateCpsRebateDiscountsRequest()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CreateCpsRebateDiscounts_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HowellRpcServiceCreateCpsRebateDiscountsArgs(%+v)", *p)

}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) DeepEqual(ano *HowellRpcServiceCreateCpsRebateDiscountsArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsArgs) Field1DeepEqual(src *CreateCpsRebateDiscountsRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type HowellRpcServiceCreateCpsRebateDiscountsResult struct {
	Success *CreateCpsRebateDiscountsResponse `thrift:"success,0,optional" frugal:"0,optional,CreateCpsRebateDiscountsResponse" json:"success,omitempty"`
}

func NewHowellRpcServiceCreateCpsRebateDiscountsResult() *HowellRpcServiceCreateCpsRebateDiscountsResult {
	return &HowellRpcServiceCreateCpsRebateDiscountsResult{}
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) InitDefault() {
	*p = HowellRpcServiceCreateCpsRebateDiscountsResult{}
}

var HowellRpcServiceCreateCpsRebateDiscountsResult_Success_DEFAULT *CreateCpsRebateDiscountsResponse

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) GetSuccess() (v *CreateCpsRebateDiscountsResponse) {
	if !p.IsSetSuccess() {
		return HowellRpcServiceCreateCpsRebateDiscountsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateCpsRebateDiscountsResponse)
}

var fieldIDToName_HowellRpcServiceCreateCpsRebateDiscountsResult = map[int16]string{
	0: "success",
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_HowellRpcServiceCreateCpsRebateDiscountsResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewCreateCpsRebateDiscountsResponse()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CreateCpsRebateDiscounts_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HowellRpcServiceCreateCpsRebateDiscountsResult(%+v)", *p)

}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) DeepEqual(ano *HowellRpcServiceCreateCpsRebateDiscountsResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *HowellRpcServiceCreateCpsRebateDiscountsResult) Field0DeepEqual(src *CreateCpsRebateDiscountsResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

type HowellRpcServiceMGetCpsRebateDiscountsArgs struct {
	Req *MGetCpsRebateDiscountsRequest `thrift:"req,1" frugal:"1,default,MGetCpsRebateDiscountsRequest" json:"req"`
}

func NewHowellRpcServiceMGetCpsRebateDiscountsArgs() *HowellRpcServiceMGetCpsRebateDiscountsArgs {
	return &HowellRpcServiceMGetCpsRebateDiscountsArgs{}
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) InitDefault() {
	*p = HowellRpcServiceMGetCpsRebateDiscountsArgs{}
}

var HowellRpcServiceMGetCpsRebateDiscountsArgs_Req_DEFAULT *MGetCpsRebateDiscountsRequest

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) GetReq() (v *MGetCpsRebateDiscountsRequest) {
	if !p.IsSetReq() {
		return HowellRpcServiceMGetCpsRebateDiscountsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) SetReq(val *MGetCpsRebateDiscountsRequest) {
	p.Req = val
}

var fieldIDToName_HowellRpcServiceMGetCpsRebateDiscountsArgs = map[int16]string{
	1: "req",
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_HowellRpcServiceMGetCpsRebateDiscountsArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewMGetCpsRebateDiscountsRequest()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("MGetCpsRebateDiscounts_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HowellRpcServiceMGetCpsRebateDiscountsArgs(%+v)", *p)

}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) DeepEqual(ano *HowellRpcServiceMGetCpsRebateDiscountsArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsArgs) Field1DeepEqual(src *MGetCpsRebateDiscountsRequest) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type HowellRpcServiceMGetCpsRebateDiscountsResult struct {
	Success *MGetCpsRebateDiscountsResponse `thrift:"success,0,optional" frugal:"0,optional,MGetCpsRebateDiscountsResponse" json:"success,omitempty"`
}

func NewHowellRpcServiceMGetCpsRebateDiscountsResult() *HowellRpcServiceMGetCpsRebateDiscountsResult {
	return &HowellRpcServiceMGetCpsRebateDiscountsResult{}
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) InitDefault() {
	*p = HowellRpcServiceMGetCpsRebateDiscountsResult{}
}

var HowellRpcServiceMGetCpsRebateDiscountsResult_Success_DEFAULT *MGetCpsRebateDiscountsResponse

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) GetSuccess() (v *MGetCpsRebateDiscountsResponse) {
	if !p.IsSetSuccess() {
		return HowellRpcServiceMGetCpsRebateDiscountsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) SetSuccess(x interface{}) {
	p.Success = x.(*MGetCpsRebateDiscountsResponse)
}

var fieldIDToName_HowellRpcServiceMGetCpsRebateDiscountsResult = map[int16]string{
	0: "success",
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_HowellRpcServiceMGetCpsRebateDiscountsResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewMGetCpsRebateDiscountsResponse()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("MGetCpsRebateDiscounts_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HowellRpcServiceMGetCpsRebateDiscountsResult(%+v)", *p)

}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) DeepEqual(ano *HowellRpcServiceMGetCpsRebateDiscountsResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *HowellRpcServiceMGetCpsRebateDiscountsResult) Field0DeepEqual(src *MGetCpsRebateDiscountsResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
